export const CITIES_BY_COUNTRY = {
  AR: [
    'Buenos Aires',
    'Córdoba',
    'Rosario',
    'Mendoza',
    'La Plata',
    'Tucumán',
    'Salta',
    'Santa Fe',
    'Mar del Plata',
    'Quilmes',
    'San Juan',
    'Resistencia',
    'Neuquén',
    'Santiago del Estero',
    'Corrientes',
  ],
  CL: [
    'Santiago',
    'Puente Alto',
    'Antofagasta',
    'Viña del Mar',
    'Valparaíso',
    'Chillán',
    'Coquimbo',
    'Puerto Montt',
    'Temuco',
    'Iquique',
    'La Serena',
    'Concepción',
    'Rancagua',
    'Talca',
    'Arica',
    'Valdivia',
  ],
  CO: [
    'Bogotá',
    'Medellín',
    'Cali',
    'Barranquilla',
    'Cartagena',
    'Cúcuta',
    'Bucaramanga',
    'Pereira',
    'Manizales',
    'Ibagué',
    'Santa Marta',
    'Bello',
    'Pasto',
    'Neiva',
    'Soledad',
  ],
  MX: [
    'Ciudad de México',
    'Guadalajara',
    'Monterrey',
    'Puebla',
    'Tijuana',
    'León',
    'Juárez',
    'Zapopan',
    'Mérida',
    'San Luis Potosí',
    'Aguascalientes',
    'Hermosillo',
    'Saltillo',
    'Mexicali',
    'Querétaro',
  ],
  PE: [
    'Lima',
    'Arequipa',
    'Trujillo',
    'Chiclayo',
    'Piura',
    'Iquitos',
    'Cusco',
    'Ayacucho',
    'Huancayo',
    'Tacna',
    'Ica',
    'Huánuco',
    'Tarapoto',
    'Juliaca',
    'Pucallpa',
  ],
  UY: [
    'Montevideo',
    'Salto',
    'Paysandú',
    'Rivera',
    'Las Piedras',
    'Maldonado',
    'Tacuarembó',
    'Melo',
    'Mercedes',
    'Artigas',
    'Soriano',
    'Cerro Largo',
    'Rocha',
    'Lavalleja',
    'Flores',
  ],
  PY: [
    'Asunción',
    'Ciudad del Este',
    'Luque',
    'San Antonio',
    'Encarnación',
    'Fernando de la Mora',
    'Lambaré',
    'Pedro Juan Caballero',
    'Villarrica',
    'Villa Elisa',
    'San Lorenzo',
    'Capiatá',
    'Itauguá',
    'Hernandarias',
    'Presidente Franco',
  ],
  BO: [
    'La Paz',
    'Santa Cruz de la Sierra',
    'Cochabamba',
    'Sucre',
    'Tarija',
    'Potosí',
    'Oruro',
    'Trinidad',
    'Riberalta',
    'Cobija',
    'El Alto',
    'Suceve',
    'Tarija',
    'Montero',
    'Yacuiba',
  ],
  EC: [
    'Quito',
    'Guayaquil',
    'Cuenca',
    'Santo Domingo',
    'Machala',
    'Durán',
    'Loja',
    'Ambato',
    'Riobamba',
    'Portoviejo',
    'Manta',
    'Esmeraldas',
    'Latacunga',
    'Quevedo',
    'Ibarra',
  ],
  BR: [
    'São Paulo',
    'Rio de Janeiro',
    'Brasília',
    'Salvador',
    'Fortaleza',
    'Belo Horizonte',
    'Manaus',
    'Curitiba',
    'Recife',
    'Goiânia',
    'Belém',
    'Porto Alegre',
    'Guarulhos',
    'Campinas',
    'São Luís',
  ],
};

export const getCitiesByCountry = (countryCode) =>
  CITIES_BY_COUNTRY[countryCode] || [];